#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Mian's Blog

# Name of the author
author: Mian Qin

# Short bio or description (displayed in the header)
description: Architecture and system

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/MQ_LOGO.jpg

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Home: ""
  Archive: "CloudCategories"
  Search: "search"
  About Me: "about"

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: celery1124@aggienetowrk.com
  facebook:
  flickr:
  github: celery1124
  instagram:
  linkedin: mianqin
  pinterest:
  rss: rss
  twitter: 
  stackoverflow: 
  youtube: channel/UCDty9L5MSnLoM8zzVB6u2Hw
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-SC2LGRF18K

# Used for Sitemap.xml and your RSS feed
url: http://celery1124.github.io
enforce_ssl: https://celery1124.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: 

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

## comments

# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
staticman_url: https://github-io-comments.herokuapp.com/v2/entry/celery1124/celery1124.github.io/master/comments

# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
reCaptcha:
  enabled: true
  siteKey: 6Le2eIMbAAAAADoV9HDpR31i8ZwInZoEb_91vEag
  secret: B1rCM9UqEhUq9QMzvqr5GSs06+MVHuAsV36XvCVpqX+xpjymlJIoHsr+ShDDxCqY8h77JvHFNpAuVH/BDwpsWhYh6Gjb1k+T82u6DhRavQmKKbOBkWqFRBu0tFbAwo1pGjndO1aTt/QigDlnkAK8e2XpGSH5357tE5ng302ETwA5iy25GCL00QW5ffOADpkQSjWBAPk1mu5M5rzcqeFYgpS+QHd3prAxOnnfTCJobSBxsI0RDJ37Cm8I9WK9rAEb0pxUYFYSvXiNiQpAuyHCM7PUt3sMANhgUzRTU8bSiWsxzuiFpvicGLRq/kPuzfyrd3ZMSxZzVpliILkfa3dXaEkqRHPmE4EpeifFB1a2SzPUchGlNmXPOmAei1nYeJYG7cPA0qpnO+6unXe2rVZTt9Xsdq7rRHuS/CTJCbDiBoU50MS0U8n5e8CTW4RdC5C5aUtFbirNMMp1QsglYSTUVB6b03BuBTrsLQqhjFCUBkuLq+c5qlKaAkLu9eSsbqziOq2BINNbQmd2dZSU8oas4YFDsj7IF9P8jpcTuswvik6/EKvFm122Fu6fq/w+kBGG8ouKR0cjWy1cedk5+UD4ik594TmBzOFldQjeWX0EsFRFm/fBMtnL7nHPWlFme/fEVm/YcyX3IA79ZaAS7Ock6SkT5aQlxuhIeyeWPgq59cU=

defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      comments: true